# -*- coding: utf-8 -*-
"""roletacassino.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1J8ASfoqDd52jOYgPkMQlltWt-MG-TPde
"""
from random import randint
from projeto import Connection

connections= Connection()

connections.db()

conexao= connections.dbConnection


sql = "INSERT INTO logscasino (numero_aposta, valor_aposta, resultado) VALUES (%s, %s, %s)"


def saveDados(conexao, numero_aposta, valor_aposta, resultado):

  cursor = conexao.cursor()

  values = (numero_aposta, valor_aposta, resultado)
  cursor.execute(sql, values)
 
  cursor.close()
  conexao.commit()

fichas= 10000

while fichas >0:
  numeroApostado= randint(1, 50)
  #numeroApostado= input('Digite numero que deseja apostar entre 1 e 50:')
    
  if int(numeroApostado)>0 and int(numeroApostado) <=50:
  #if numeroApostado.isdigit() == True and (int(numeroApostado)>0 and int(numeroApostado) <=50):
    
    validado = False
    while validado == False:

      print('Seu saldo é:', fichas)
        
      valorAposta= randint(1, fichas)
      #valorAposta= input('Digite o valor da aposta:')
      
      if int(valorAposta) <= int(fichas) and int(valorAposta) >0:
      #if valorAposta.isdigit() == True and (int(valorAposta) <= int(fichas) and int(valorAposta) >0):
            
        numberOutput = randint(1, 50)
        print(numberOutput)
          
        if numberOutput != numeroApostado:
          fichas= int(fichas) - int(valorAposta)
          print('Você Perdeu!')
              
          saveDados(conexao, numeroApostado, valorAposta, 0)
          
        else:
          fichas= fichas + (valorAposta*50)
          print('Você Ganhou!')
            
          saveDados(conexao, numeroApostado, valorAposta, 1)
        
          print(fichas)
        break

      else:
        print('Aposte um número de ficha que possua!')   
        
  else:
    print('Aposte um numero correto entre 1 e 50!')        
  

print('voce perdeu tudo')

conexao.close()